version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: meditrack-db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=meditrack
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./postgres-data:/var/lib/postgresql/data